let db = {
  en: {
    slide_1: {
      headline_1: "The center of the metaverse.",
      copy_1: "Gamium is the first Decentralized Social Metaverse that interconnects all Metaverses. Thanks to web3, Gamium unites different virtual worlds where your Avatar's dreams come true: the only limit is your imagination.",
      button_1: "Whitepaper",
      clickme_1: "Click",
      clickme_2: "Start the journey.",
    },
    slide_2: {
      button_1: "Read more",
      headline_1: "The virtual world of your dreams.",
      copy_1: "Imagine creating your own Ready Player One from scratch. Gamium is building a fully immersive and decentralized 3D world for its Avatars to have fun, explore, socialize, earn achievements, innovate and create with no limits.",
    },
    slide_3: {
      headline_1: "The Avatar: your Digital Identity.",
      copy_1: "Gamium allows you to have a complete Digital Identity you can use in any web3 or Metaverse application, thus traveling with no restriction in the new internet. Link on-chain and off-chain data to your Avatar and customize your anatomy.",
      button_1: "Read more",
      headline_2: "Get your Metaverse passport now.",
      copy_2: "Connect to any web3 or Metaverse application with your Avatar. Bring your ASSETs, data, and anatomies all over the new internet.",
      button_2: "Read more",
    },
    slide_4: {
      headline_1: "Genesis, a bridge between the physical and virtual world",
      copy_1: "Genesis city is the center of the Gamium world, where you can find the Genesis Buildings. Inside these buildings, you can use exclusive applications and experience amazing experiences in the Metaverse, such as attending your superstar event, going to conferences, visiting a museum, shopping or networking.",
      button_1: "Read more",
      headline_2: "Socialize to Earn: rewards for socializing",
      copy_2: "Thanks to Gamiumâ€™s pioneer idea of Socialize to Earn, socializing online has evolved. Your interactions have value; thatâ€™s why in Gamium you can enjoy a fun and gamified experience while monetizing your social interactions.",
      button_2: "Read more",
    },
    slide_5: {
      button_1: "Tokenomics",
      headline_1: "Gamiumâ€™s economy: $GMM and $MST.",
      copy_1: "Gamiumâ€™s economy is empowered by two tokens, GMM is the Gamium governance and medium of exchange token, while MST is the utility and reward token in the heart of the Gamium economy. With GMM, you can govern the Metaverse, access exclusive events, receive NFT and token airdrops and many more.",
    },
    burger_menu: {
      tokens_1: "Governance token",
      tokens_2: "Reward token",
      closeIcon: "Close",
      launch_AGE: "Read more",
      launch_app: "Launch App",
      input_text: "Stay in the loop",
      input_btn: "Sign up",
      input_thanks: "Your registration has been submited. Thank you!",
      sections_title: "Sections",
      section_1: "Gamium",
      section_2: "Social Metaverse",
      section_3: "Avatar",
      section_4: "Social Features",
      section_5: "Economy",
      resources_title: "Resources",
      resource_1: "Whitepaper",
      resource_2: "Roadmap",
      resource_3: "Tokenomics",
      social_media_title: "Social Media",
      social_1: "Instagram",
      social_2: "Twitter",
      social_3: "Discord",
      social_4: "Telegram",
      social_5: "Medium",
    },
    ani_controls: {
      slide_down: "Slide down",
      scroll_down: "Scroll down",
    },
    page_error:{
      err_404_1: "METAVERSE",
      err_404_2: "NOT",
      err_404_3: "FOUND",
      desc_404_1: "IT LOOKS LIKE YOU CROSSED A GLITCHY PORTAL.",
      err_403_1: "METAVERSE",
      err_403_2: "ACCESS",
      err_403_3: "DENIED",
      desc_403_1: "IT LOOKS LIKE THIS GATE IS FORBIDDEN FOR SOME REASON.",
      err_500_1: "METAVERSE",
      err_500_2: "UNEXPECTED",
      err_500_3: "ERROR",
      desc_500_1: "THINGS ARE A LITTLE UNSTABLE HERE.",
      desc_500_2: "WE SUGGEST COME BACK LATER.",
      desc_help_you: "LET US HELP YOU GUIDE YOU OUT.",
      btn_back: "BACK",
      btn_home: "HOME",
    },
    nav_bar:{
      faqs: "FAQ",
      careers: "Careers",
      press_partners: "Press & Partners",
    },
    press_partners:{
      press: "Press",
      partners: "Partners",
    },
    careers:{
      careers_title: "Careers",
      career_text: "Would you like to join a young project, with a great vision in which the limit of creation goes beyond your imagination? Are </br> you looking to boost your growth by the hands of the creators of the future? Then GAMIUM is your next big challenge!",
      jobs_title: "Now open",
      button_1: "What's in it for you?",
      button_2: "Apply now",
      button_3: "See more",
      job_1:{
        title: "UNITY DEVELOPER",
        type: "IT",
        text_1: "â€¢	At least 5 year of experience in game development",
        text_2: "â€¢	Experience with Unity3D engine (editor and scripting)",
        text_3: "â€¢	Build mobile apps from the ground up for iOS and Android using Unity",
        text_4: "â€¢	Good knowledge of C# or another OOP language",
        text_5: "â€¢	Good knowledge regarding design patterns",
        text_6: "â€¢	Solid understanding of maths involved in computer graphics",
        text_7: "â€¢	Provide technical leadership in areas of specialization and assist other areas with technical questions",
        text_8: "â€¢	Extensive Debugging Knowledge",
        text_9: "â€¢	Knowledge of gameplay programming",
        text_10: "Additional things we will consider are ...",
        clear_space: "",
        text_11: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_12: "â€¢	You have worked with international teams",
        text_13: "â€¢	You are fluent both in English and Spanish and/or other languages",
        text_14: "â€¢	Leadership capacity",
        text_15: "â€¢	Experience in team management",
      },
      job_2:{
        title: "DEVOPS EXPERT",
        type: "IT",
        text_1: "â€¢	Broad background in Linux operating system (Debian-like)",
        text_2: "â€¢	Research infrastructure solutions in Google Cloud Platform Services (GCP)",
        text_3: "â€¢	Manage Kubernetes/Full Instances clusters and continuously improve the deployment process of our applications",
        text_4: "â€¢	Develop and improve our monitoring and alerting systems",
        text_5: "â€¢	NGINX, WSGI, ASGI, CELERY servers management",
        text_6: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, RabbitMQ, Redis, ...) management knowledge",
        text_7: "â€¢	Administration of GCP resources including provisioning, monitoring and maintenance",
        text_8: "â€¢	Git version control",
        text_9: "Additional things we will consider are ...",
        text_10: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_11: "â€¢	You have worked with international teams",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_3:{
        title: "FRONTEND DEVELOPER",
        type: "IT",
        text_1: "â€¢	Broad background in programing in JS6, REACT, VUE ...",
        text_2: "â€¢	CSS artistry capabilities",
        text_3: "â€¢	Consumption of REST API and WS ",
        text_4: "â€¢	Web3 knowledge, including DAPS development experience",
        text_5: "â€¢	Understanding of problems associated with distributed virtual environments (Docker and Cloud Instances)",
        text_6: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, Redis, ...) knowledge",
        text_7: "â€¢	Git version control",
        text_8: "Additional things we will consider are ...",
        text_9: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_10: "â€¢	You have worked with international teams",
        text_11: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_4:{
        title: "PYTHON / DJANGO DEVELOPER",
        type: "IT",
        text_1: "â€¢	Broad background in programing Python 3 and understanding of its module ecosystem",
        text_2: "â€¢	Django framework knowledge",
        text_3: "â€¢	Celery task distribution (using AMPQ backend)",
        text_4: "â€¢	Both creation and consumption of REST API and WS (Django Channels, Django Restframework) and OAUTH2.0",
        text_5: "â€¢	Web3 knowledge",
        text_6: "â€¢	Understanding of problems associated with distributed virtual environments (Docker and Cloud Instances)",
        text_7: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, Redis, ...) knowledge",
        text_8: "â€¢	Git version control",
        text_9: "Additional things we will consider are ...",
        text_10: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_11: "â€¢	You have worked with international teams",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_5:{
        title: "3D GENERALIST",
        type: "MARKETING",
        text_1: "â€¢	Must be a strong and experienced 3d generalist with experience working in a fast-paced environment",
        text_2: "â€¢	Relevant technical training in different fields of the 3d production",
        text_3: "â€¢	Knowledge of 3d modeling software",
        text_4: "â€¢	Knowledge of texturing and shading software",
        text_5: "â€¢	Knowledge of lighting and rendering software",
        text_6: "â€¢	Knowledge of editing and compositing software, in 3d and 2d",
        text_7: "â€¢	Strong understanding of 3d production workflows, storage, asset management and archive",
        text_8: "â€¢	Excellent written and verbal communication skills",
        text_9: "â€¢	Previous experience in an agency or video/animation production company",
        text_10: "Additional things we will consider are ...",
        text_11: "â€¢	You have worked with international teams.",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_6:{
        title: "3D VIDEO EDITOR",
        type: "MARKETING",
        text_1: "â€¢	Must be a strong and experienced video editor and motion designer with experience working in a fast-paced environment",
        text_2: "â€¢	Relevant technical training in video and digital design/production.",
        text_3: "â€¢	Knowledge of Adobe Creative Cloud, specifically Premiere, After Effects, Photoshop, and Illustrator",
        text_4: "â€¢	Color correction and grading skills",
        text_5: "â€¢	Strong understanding of post-production workflows, storage, asset management and archive",
        text_6: "â€¢	Excellent written and verbal communication skills",
        text_7: "â€¢	Previous experience in an agency or video/animation production company",
        text_8: "Additional things we will consider are ...",
        text_9: "â€¢	You have worked with international teams.",
        text_10: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_7:{
        title: "AGILE COACH / SCRUM MASTER",
        type: "IT",
        text_1: "â€¢	Manage all aspects of project development for multiple digital initiatives for a variety of internal clients.",
        text_2: "â€¢	Develop and demonstrate an understanding of the customer business, needs, expectations, and success factors.",
        text_3: "â€¢	Schedule and manage all resources required to develop the project and ensure timely integration, productivity, and efficient use of resources",
        text_4: "â€¢	Deliver projects on time, on budget, and within scope, while adhering to the standard development and design process of the company",
        text_5: "â€¢	Main contact for client and internal communications regarding project deliverables, status, financial status",
        text_6: "â€¢	Completes agreed work within established estimates and communicates status and issues promptly",
        text_7: "Requirements:",
        text_8: "â€¢	Leadership experience as Scrum Master or in a similar function",
        text_9: "â€¢	Project management certification (PMP or equivalent) is a plus",
        text_10: "â€¢	Solid understanding of the design processes for digital solutions as well as creative production and deliverables. Including UX Resarch, UX and UI Design",
        text_11: "â€¢	Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies",
        text_12: "â€¢	Solid understanding of the full web design and mobile development life cycle",
        text_13: "â€¢	Ability to facilitate a solution-oriented approach to managing projects",
        text_14: "â€¢	Excellent communication skills with the ability to effectively convey complex information at all levels",
        text_15: "â€¢	Strong experience with MS Tools: MS Project, Visio, Powerpoint, Word, Excel",
        text_16: "â€¢	Agile Development Methodologies and tools (Confluence, Planner)",
        text_17: "We will additionally consider:",
        text_18: "â€¢	Onsite/offshore and outsourcing experience.",
        text_19: "â€¢	Passion and knowledge to motivate your team with a servant-leadership style",
        text_20: "â€¢	Enjoy working with interdisciplinary teams in a dynamic environment and appreciate the ex-change with specialists in blockchain, programming and 3D development",
        text_21: "â€¢	Several years of experience in agile software development, ideally in an international scaled environment, and you would like to make a big difference by taking responsibility for coordination and organization",
      },
      job_8:{
        title: "CFO",
        type: "MANAGEMENT",
        text_1: "â€¢	Working alongside the CEO and Board of Directors",
        text_2: "â€¢	Create and present financial and tax strategy recommendations to CEO",
        text_3: "â€¢	Play an integral role in leading all internal and external financial decisions as the company continues to expand",
        text_4: "â€¢	Leading all outward-facing financing activities and communications of the company with current and prospective investors, investment bankers, and capital markets",
        text_5: "â€¢	Assess and evaluate financial performance with regards to both short-term and long-term growth targets and operational KPI's, budgets and forecasts",
        text_6: "â€¢	Ensure compliance with the law and company's policies",
        text_7: "â€¢	Cooperates with Legal and Tax Advisors",
        text_8: "â€¢	Prepare financial statements and reports",
        text_9: "â€¢	Ensure legal compliance on all financial functions",
        text_10: "â€¢	Manage relationships with banks",
        text_11: "â€¢	Building a risk management",
        text_12: "Requirements:",
        text_13: "â€¢	3+ years' experience in Executive Finance Management",
        text_14: "â€¢	Previous experience as CFO or similar; preferably within a growth-stage start-up",
        text_15: "â€¢	Really high interest in the crypto market and derivatives (DeFi, smartcontracts, NTFs, ...) ",
        text_16: "â€¢	Previous experience of building and managing small teams",
        text_17: "â€¢	Some understanding of various business functions: sales, marketing, law and operations",
        text_18: "â€¢	Experience working in a multicultural environment",
        text_19: "â€¢	Outstanding organisational and leadership skills",
        text_20: "â€¢	Excellent interpersonal and communication skills",
        text_21: "â€¢	You are fluent both in English and Spanish and/or other languages.",
      },
      job_9:{
        title: "PR & COMMUNICATION MANAGER (FREELANCE)",
        type: "MARKETING",
        text_1: "â€¢	Relevant technological articles in Tier 1 news media",
        text_2: "â€¢	Knowledge of web3, blockchain and metaverse",
        text_3: "â€¢	Very well connected in the media and press industry",
        text_4: "Additional things we will consider are ...",
        text_5: "â€¢	You have worked with international teams.",
        text_6: "â€¢	You are fluent both in English and Spanish and/or other languages.",
        text_7: "â€¢	Leadership capacity",
        text_8: "â€¢	Experience in team management",
      },
      // The rest of jobs
      popup:{
        title: "WHAT'S IN IT FOR YOU?",
        title_text_1: "High Standards: ",
        text_1: "we accept the challenge of learning day by day, improving in our roles and how to add value to the future! We enjoy working driven by motivation for the project, teamwork and constant development.",
        title_text_2: "Colleagues/Team: ",
        text_2: "we are a young and dynamic community that enjoys co-creating and developing the technology of the future, supported by the best professionals full of talent, enthusiasm and vision facing new challenges. Inside Gamium, fun, collaboration, a good atmosphere and professionalism runs together.",
        title_text_3: "Growth and Development: ",
        text_3: "we want the person who joins our team to know the internal processes and the business, and to be able to grow and develop with us, working in a environment in which talent is breathed in every corner inside Gamium. The motivation for the Project, the energy and the desire to learn are keys to being part of Gamium's team.",
        title_text_4: "Self-organization: ",
        text_4: "we believe in Independence to carry out our tasks. We pursue our goals and insist on giving the best version of ourselves while build the future inside Gamium.",
        title_text_5: "Flexibility: ",
        text_5: "at Gamium we care about the well-being of our contributors and therefore we know how to combine our work with personal life to be more effective, we are flexible because we all have a common goal and we are committed to the project.",
        title_text_6: "Fully Remote: ",
        text_6: "we believe in remote work as part of our team will be doing it from Barcelona and from Bali, so you can work from wherever you prefer and feel more productive and committed to the roles to be played.",
        title_text_7: "Competitive salary: ",
        text_7: "we offer you a fixed and variable salary in Tokens (valuable according to profile and experience).",
        button: "Close",
      },
    },
    faqs:{
      nav_bar:{
        nav_bar_title: "About",
        nav_bar_element_1: "Gamium",
        nav_bar_element_2: "The Avatar",
        nav_bar_element_3: "The Metaverse",
        nav_bar_element_4: "Tokens",
        nav_bar_element_5: "LAND's",
      },
      faqs_body:{
        element_1:{
          title: "Gamium",
          faq_0:{
            title: "What is Gamium?",
            text_1: "Gamium is a web3 and metaverse technology company whose mission is to create the first metaverse that interconnects all of them, making avatars and assets multi-metaverse compatible.",
          },
          faq_1:{
            title: "Where does Gamium's name come from?",
            text_1: "We are building the social foundation of web3 and the metaverse. Different that current social platforms, we want to create 'healthy' technology that adds value to society, but at the same time we know that technologies have to have some kind of entertainment. The solution? The perfect mix of 'Premium' and 'Gamification'.  Gamium!",
          },
          faq_2:{
            title: "Which technology is Gamium developing?",
            text_1: "- The Avatar: A digital identity that can be used across all web3 and metaverse applications, allowing unique interoperability and usability.",
            text_2: "- The Decentralized Social Metaverse: A virtual world to enable everyone to build whatever they want through the Gamium SDK.",
          },
          faq_3:{
            title: "How many fungible tokens does Gamium have?",
            text_1: "Gamium has 2 tokens:",
            text_2: "- GMM: The governance and medium of exchange token of the entire Gamium ecosystem.",
            text_3: "- MST: The utility token of the Gamium Metaverse.",
          },
          faq_4:{
            title: "How many non-fungible tokens (NFTs) does Gamium have?",
            text_1: "- Avatars: The digital identity of humans. Soulmate NFT (non-transferable).",
            text_2: "- LANDs: Pieces of LAND of the Gamium Metaverse.",
            text_3: "- Buildings: 3D buildings to use in any metaverse.",
            text_4: "- ASSETs: 3D objects to use in any metaverse.",
          },
          faq_5:{
            title: "Is Gamium free?",
            text_1: "The only requirement to use Gamium is to have an Avatar - digital identity. So the users will need to mint their Avatar to use the vast majority of its features. The avatar is not free in order to avoid bots attacking our ecosystem (if they attack it, at least they have to pay for it). The cost of minting will be very low.",
          },
          faq_6:{
            title: "Do you need an Avatar to access the Gamium Metaverse?",
            text_1: "Yes, the Avatar technology enables incredible functionality for metaverses, that's why it is a requirement to have an Avatar to access the Gamium Metaverse.",
          },
          faq_7:{
            title: "What's included in the Gamium ecosystem?",
            text_1: "The Gamium ecosystem includes the Gamium Metaverse and all the applications that integrate our Avatar SDK.",
          },
          faq_8:{
            title: "What is Socialize to Earn?",
            text_1: "Like the play-to-earn model, our economy potentiates what we call socialize to earn, where Avatars can monetize the value created by their social interactions.",
          },
          faq_9:{
            title: "Who is the team behind Gamium?",
            text_1: "Our team comprises young visionary people with very high technical skills needed to develop new innovating technologies. We're a team of dreamers with one objective in mind: building the technology of tomorrow. ",
            text_2: "https://whitepaper.gamium.world/details/team",
          },
          faq_10:{
            title: "Who are the main Partners and Investors of Gamium?",
            text_1: "DAO Maker, Metrix Capital, Magnus Capital, Vent Finance, Master Ventures, Venly , Unanimous VC, Peech Capital, ZBS Capital, RR2, Atesis Capital, Parachain Ventures, Mr Beast , Willyrex, Anthony Pompliano, Healthy Pockets, Kmanu, Reven, The Moon Carl, Dustin Plantholt, Diario Cripto, Supra Oracles, GameRich, Zoopa, and many more.",
          },
          faq_11:{
            title: "How many non-fungible tokens (NFTs) does Gamium have?",
            text_1: "-Avatars: The digital identity of humans. Soulmate NFT (non-transferable)",
            text_2: "-LANDs: Pieces of LAND of the Gamium Metaverse.",
            text_3: "-Buildings: 3D buildings to use in any metaverse.",
            text_4: "-ASSETs: 3D objects to use in any metaverse.",
          }
        },
        element_2:{
          title: "The Avatar",
          faq_1:{
            title: "What is the Avatar?",
            text_1: "The Avatar is a digital identity represented by a soulmate NFT that brings all the digital fingerprints of a user into a unified entity. These digital fingerprints include 3D anatomies, and on-chain and off-chain data.",
          },
          faq_2:{
            title: "Which technologies does the Avatar use?",
            text_1: "NFT, blockchain technology, digital signatures, AI, data modeling, forensics analysis.",
          },
          faq_3:{
            title: "What type of data is stored in the Avatar?",
            text_1: "On-chain and Off-chain data.",
          },
          faq_4:{
            title: "What kind of data can Avatars store?",
            text_1: "All the On-chain data transactions. With our data modeling, we can extract transactions, holdings, protocols used, holder scores, DeFi scores, NFTs holding, user profiles, latent representations, transactions graphs, and many more.",
            text_2: "All types of Off-chain data, like social media information (followers, friends ...), gaming information, Education degrees, medical records... Infinite possibilities.",
          },
          faq_5:{
            title: "How is the data structured?",
            text_1: "All the Avatar data is structured into useful KPIs - achievements. This KPIs can be accessed through API call using the Avatar SDK.",
          },
          faq_6:{
            title: "How to set up Avatar privacy?",
            text_1: "Every user can assign the privacy of each KPIs. We are true believers of privacy.",
          },
          faq_7:{
            title: "Does the Avatar has a 3D representation?",
            text_1: "Yes! Apart from the data aspect, an Avatar has also anatomies, which are 3D representations that represent the Avatar on a 3D environment.",
          },
          faq_8:{
            title: "Can I customize it?",
            text_1: "Every Avatar can have multiple anatomies from different providers. Some are more realistic, other more low poly. The users can customize these anatomies whenever they want.",
          },
          faq_9:{
            title: "What is the Avatar SDK?",
            text_1: "The Avatar SDK is the tool used by applications to integrate The Avatar digital identities. This tool includes a social login (like login with Facebook) in which when logged in to any application, the user can give permission to the application to access specific information from their Avatar data. This information can be used by the application to increase the value of their products or services.",
          },
          faq_10:{
            title: "What applications can use the Avatar SDK?",
            text_1: "Literally, any web3 or metaverse application can integrate our Avatar SDK.",
            text_2: "Examples that applications that can start using our SDK are Launchpads, DeFi apps, Jobs portals, DAOs ...",
          },
        },
        element_3:{
          title: "The Metaverse",
          faq_1:{
            title: "What is a Social Metaverse?",
            text_1: "A social metaverse is a metaverse focused on social interactions and social features.",
          },
          faq_2:{
            title: "How does the Gamium Metaverse look like?",
            text_1: "The Gamium Metaverse is composed by Genesis, Islands and Community servers. Genesis is at the center surrounded by Islands.",
          },
          faq_3:{
            title: "What can we find in Genesis?",
            text_1: "Genesis is the place at the center of the Gamium world where you can find the Gamium Buildings. In Genesis, you will also find immersive experiences and exclusive daily events.",
          },
          faq_4:{
            title: "What are the Gamium Buildings?",
            text_1: "These buildings contain unique applications like Decentralized chats, 3D calling apps, DeFi Applications and Jobs portals. ",
          },
          faq_5:{
            title: "What can we find in the Islands?",
            text_1: "Outside of Genesis there are Islands, which are exclusive places for Avatars to live and build whatever they want. Using the Gamium SDK into their LAND, Avatars are able to build their house, create 3D objects, create exclusive events, integrate their ecommerce store, advertise or rent their space and many more.",
          },
          faq_6:{
            title: "What are Community Servers?",
            text_1: "Community servers are exclusive cities for communities. You have to be member of that community to access the Community Server. Community members can interact and build with the Gamium SDK as well. More exciting information will be revealed soon.",
          },
          faq_7:{
            title: "Will it be easy to build something in the Gamium Metaverse?",
            text_1: "Yes, we are developing a easy to use Gamium SDK for our Avatars.",
          },
          faq_8:{
            title: "What is the Gamium SDK?",
            text_1: "The Gamium SDK is a no-code building tool. Avatars will be able to build 3D ASSETs, experiences and connect applications with the Gamium SDK.",
          },
          faq_9:{
            title: "Who owns the Gamium Metaverse?",
            text_1: "The Gamium Metaverse is owned by Avatars. The majority of experiences, applications and ASSETs of the metaverse are by Avatars for Avatars.",
          },
          faq_10:{
            title: "Where I can find The LANDs and Buildings?",
            text_1: "The majority of LANDs will be located on the Islands. Buildings can be located everywhere in the Metaverse. You can move the Buildings you own into your LAND.",
          },
          faq_11:{
            title: "Is there an NFT marketplace?",
            text_1: "Yes, the Gamium Metaverse has a native NFT marketplace for LANDs, Buildings and ASSETs.",
          },
          faq_12:{
            title: "Anyone can create their own ASSETs and trade them on the marketplace?",
            text_1: "Yes, All the Avatars can create 3D ASSETs and upload them to our NFT marketplace (we will make sure to handle the minting for you). Avatars can also create collections and add royalties for the secondary sales.",
          },
        },
        element_4:{
          title: "Tokens",
          faq_1:{
            title: "How many fungible tokens does Gamium have?",
            text_1: "Gamium has 2 tokens:",
            text_2: "- GMM: The governance and medium of exchange token of the entire Gamium ecosystem.",
            text_3: "- MST: The utility token of the Gamium Metaverse.",
          },
          faq_2:{
            title: "How many non-fungible tokens (NFTs) does Gamium have?",
            text_1: "- Avatars: The digital identity of humans. Soulmate NFT (non-transferable).",
            text_2: "- LANDs: Pieces of LAND of the Gamium Metaverse.",
            text_3: "- Buildings: 3D buildings to use in any metaverse.",
            text_4: "- ASSETs: 3D objects to use in any metaverse.",
          },
          faq_3:{
            title: "In which blockchains are Gamium tokens deployed?",
            text_1: "- GMM: Binance Smart Chain",
            text_2: "- MST: TBA",
            text_3: "- Avatars: Binance Smart Chain",
            text_4: "- LANDs: Ethereum",
            text_5: "- Buildings: Ethereum",
            text_6: "- ASSETs: TBA",
          },
          faq_4:{
            title: "Who has audited the tokens? ",
            text_1: "Certik, the leading global blockchain security firm.",
          },
          faq_5:{
            title: "What is GMM used for?",
            text_1: "- Avatar governance",
            text_2: "- Metaverse governance",
            text_3: "- Open community servers",
            text_4: "- Access exclusive drops",
            text_5: "- Receive airdrops",
            text_6: "- Metaverse decentralized moderation",
            text_7: "- Access exclusive events",
          },
          faq_6:{
            title: "Which is the max supply of GMM tokens and initial price?",
            text_1: "Max supply is 50,000,000,000 tokens and the initial price is 0.0003$.",
          },
          faq_7:{
            title: "When is the GMM listing?",
            text_1: "March 2022, stay tuned!",
          },
          faq_8:{
            title: "Which is the GMM token contract address?",
            text_1: "The contract address is TBA.",
          },
          faq_9:{
            title: "What is the GMM staking?",
            text_1: "It is a useful feature we will reveal very soon. Big surprise.",
          },
          faq_10:{
            title: "What is MST used for?",
            text_1: "Currency of the Gamium Metaverse. Any type of transaction inside of the Gamium Metaverse will be done with MST.",
          },
          faq_11:{
            title: "When is the MST listing?",
            text_1: "Q2 2022, stay tuned!",
          },
          faq_12:{
            title: "When will LANDs, Buildings, and ASSETs be available?",
            text_1: "We will announce it very soon. Big surprise.",
          },
          faq_13:{
            title: "Will I be able to trade LANDs, Buildings, and ASSETs NFTs on OpenSea?",
            text_1: "Yes!",
          },
        },
        element_5:{
          title: "LANDs",
          faq_1:{
            title: "How does the Gamium Metaverse look like?",
            text_1: "The Gamium Metaverse is composed by Genesis, Islands and Community servers. Genesis is at the center surrounded by Islands.",
          },
          faq_2:{
            title: "Where I can find The LANDs and Buildings?",
            text_1: "The majority of LANDs will be located on the Islands. Buildings can be located everywhere in the Metaverse. You can move the Buildings you own into your LAND.",
          },
          faq_3:{
            title: "How big are LANDs?",
            text_1: "LANDs are described in units, being 16 meters equivalent to a unit. Gamium LANDs are rectangular and have 7 different sizes: 1x1, 1x2, 2x2, 2x3, 3x3, 3x5 or 5x5.",
            text_2: "A 1x1 LAND is 16m x 16m, so 256 sqm, with a total of 100,000 square units for sale.",
          },
          faq_4:{
            title: "When will be the LANDs first sale date?",
            text_1: "The first drop will occur very soon. Every 3 weeks there will be an Island drop until all the Islands have been populated.",
          },
          faq_5:{
            title: "How LAND sales work?",
            text_1: "LANDs will be sold in drops. More specifically there will be 1 drop every 3 weeks for each of the Islands of the Gamium Metaverse. Each drop has its own thematic, style and influencers. Maybe you can have famous neighbors. There will be Presale, primary sales and secondary sales for the LANDs. We will announce it very soon.",
          },
          faq_6:{
            title: "What can you do with a LAND?",
            text_1: "â—	Build social experiences",
            text_2: "â—	Connect to internet and blockchains with one click.",
            text_3: "â—	Online shopping",
            text_4: "â—	Advertising",
            text_5: "â—	Renting",
            text_6: "â—	Neighborhood governance",
          },
          faq_7:{
            title: "Which prices will have the LANDs?",
            text_1: "There will be different prices depends on the LAND's area.",
            text_2: "We will announce it soon.",
          },
        },
      },
    },
  },
  es: {
    slide_1: {
      headline_1: "El centro del Metaverso.",
      copy_1:
        "Gamium es el primer Metaverso Social Descentralizado que interconecta todos los Metaversos. Gracias a la Web3, Gamium une diferentes mundos virtuales donde los sueÃ±os de tu Avatar se hacen realidad: el Ãºnico lÃ­mite es tu imaginaciÃ³n.",
      button_1: "Whitepaper",
      clickme_1: "Click",
      clickme_2: "Empezar el viaje",
    },
    slide_2: {
      button_1: "Leer mÃ¡s",
      headline_1: "El mundo virtual de tus sueÃ±os.",
      copy_1:
        "Imagina crear tu propio Ready Player One desde cero. Gamium estÃ¡ construyendo un mundo 3D totalmente inmersivo y descentralizado para que sus Avatares se diviertan, exploren, socialicen, obtengan logros, innoven y creen sin lÃ­mites.",
    },
    slide_3: {
      headline_1: "El Avatar: tu Identidad Digital.",
      copy_1:
        "Gamium te permite tener una Identidad Digital completa que puedes utilizar en cualquier aplicaciÃ³n Web3 o Metaverso para navegar sin restricciones por el nuevo internet. Vincula datos on y off-chain a tu Avatar y personaliza tu anatomÃ­a.",
      button_1: "Leer mÃ¡s",
      headline_2: "Consigue ya tu pasaporte del Metaverso.",
      copy_2:
        "ConÃ©ctate a cualquier aplicaciÃ³n Web3 o Metaverso con tu Avatar. Lleva contigo tus ASSETs, datos y anatomÃ­as por el nuevo internet.",
      button_2: "Leer mÃ¡s",
    },
    slide_4: {
      headline_1: "GÃ©nesis, un puente entre el mundo fÃ­sico y el virtual.",
      copy_1:
        "La ciudad de Genesis es el centro del mundo de Gamium, donde se encuentran los edificios de Genesis. Dentro de estos edificios, puedes utilizar aplicaciones exclusivas y vivir experiencias increÃ­bles en el Metaverso, como asistir a eventos de su superestrella favorita, ir a conferencias, visitar un museo, ir de compras o hacer nuevos contactos.",
      button_1: "Leer mÃ¡s",
      headline_2: "Socialize-to-Earn: recompensas por socializar.",
      copy_2:
        "Gracias a la idea pionera de Gamium del Socialize-to-Earn, la socializaciÃ³n en lÃ­nea ha evolucionado. Tus interacciones tienen valor; por eso en Gamium puedes disfrutar de una experiencia divertida y gamificada mientras monetizas tus interacciones sociales.",
      button_2: "Leer mÃ¡s",
    },
    slide_5: {
      button_1: "Tokenomics",
      headline_1: "La economÃ­a de Gamium: $GMM y $MST.",
      copy_1:
        "La economÃ­a de Gamium estÃ¡ potenciada por dos tokens, GMM es el token de gobernanza y medio de intercambio de Gamium, mientras que MST es el token de utilidad y recompensa en el corazÃ³n de la economÃ­a de Gamium. Con GMM, puedes gobernar el Metaverso, acceder a eventos exclusivos, recibir NFT y airdrops de tokens y mucho mÃ¡s.",
    },
    burger_menu: {
      tokens_1: "Governance token",
      tokens_2: "Reward token",
      closeIcon: "Cerrar",
      launch_AGE: "Leer mÃ¡s",
      launch_app: "Lanzar App",
      input_text: "No te pierdas nada",
      input_btn: "Inscribirse",
      input_thanks: "Your registration has been submited. Thank you!",
      sections_title: "Secciones",
      section_1: "Gamium",
      section_2: "Metaverso social",
      section_3: "Avatar",
      section_4: "CaracterÃ­sticas sociales",
      section_5: "EconomÃ­a",
      resources_title: "Recursos",
      resource_1: "Whitepaper",
      resource_2: "Roadmap",
      resource_3: "Tokenomics",
      social_media_title: "Redes Sociales",
      social_1: "Instagram",
      social_2: "Twitter",
      social_3: "Discord",
      social_4: "Telegram",
      social_5: "Medium",
    },
    ani_controls: {
      slide_down: "Desliza",
      scroll_down: "Scroll",
    },
    page_error:{
      err_404_1: "METAVERSE",
      err_404_2: "NOT",
      err_404_3: "FOUND",
      desc_404_1: "IT LOOKS LIKE YOU CROSSED A GLITCHY PORTAL.",
      err_403_1: "METAVERSE",
      err_403_2: "ACCESS",
      err_403_3: "DENIED",
      desc_403_1: "IT LOOKS LIKE THIS GATE IS FORBIDDEN FOR SOME REASON.",
      err_500_1: "METAVERSE",
      err_500_2: "UNEXPECTED",
      err_500_3: "ERROR",
      desc_500_1: "THINGS ARE A LITTLE UNSTABLE HERE.",
      desc_500_2: "WE SUGGEST COME BACK LATER.",
      desc_help_you: "LET US HELP YOU GUIDE YOU OUT.",
      btn_back: "BACK",
      btn_home: "HOME",
    },
    nav_bar:{
      faqs: "FAQ",
      careers: "Profesiones",
      press_partners: "Prensa & Partners",
    },
    press_partners:{
      press: "Prensa",
      partners: "Partners",
    },
    careers:{
      careers_title: "Careers",
      career_text: "Would you like to join a young project, with a great vision in which the limit of creation goes beyond your imagination? Are you looking to boost your growth by the hands of the creators of the future? Then GAMIUM is your next big challenge!",
      jobs_title: "Now open",
      button_1: "What's in it for you?",
      button_2: "Apply now",
      button_3: "See more",
      job_1:{
        title: "UNITY DEVELOPER",
        type: "IT",
        text_1: "â€¢	At least 5 year of experience in game development",
        text_2: "â€¢	Experience with Unity3D engine (editor and scripting)",
        text_3: "â€¢	Build mobile apps from the ground up for iOS and Android using Unity",
        text_4: "â€¢	Good knowledge of C# or another OOP language",
        text_5: "â€¢	Good knowledge regarding design patterns",
        text_6: "â€¢	Solid understanding of maths involved in computer graphics",
        text_7: "â€¢	Provide technical leadership in areas of specialization and assist other areas with technical questions",
        text_8: "â€¢	Extensive Debugging Knowledge",
        text_9: "â€¢	Knowledge of gameplay programming",
        text_10: "Additional things we will consider are ...",
        text_11: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_12: "â€¢	You have worked with international teams",
        text_13: "â€¢	You are fluent both in English and Spanish and/or other languages",
        text_14: "â€¢	Leadership capacity",
        text_15: "â€¢	Experience in team management",
      },
      job_2:{
        title: "DEVOPS EXPERT",
        type: "IT",
        text_1: "â€¢	Broad background in Linux operating system (Debian-like)",
        text_2: "â€¢	Research infrastructure solutions in Google Cloud Platform Services (GCP)",
        text_3: "â€¢	Manage Kubernetes/Full Instances clusters and continuously improve the deployment process of our applications",
        text_4: "â€¢	Develop and improve our monitoring and alerting systems",
        text_5: "â€¢	NGINX, WSGI, ASGI, CELERY servers management",
        text_6: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, RabbitMQ, Redis, ...) management knowledge",
        text_7: "â€¢	Administration of GCP resources including provisioning, monitoring and maintenance",
        text_8: "â€¢	Git version control",
        text_9: "Additional things we will consider are ...",
        text_10: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_11: "â€¢	You have worked with international teams",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_3:{
        title: "FRONTEND DEVELOPER",
        type: "IT",
        text_1: "â€¢	Broad background in programing in JS6, REACT, VUE ...",
        text_2: "â€¢	CSS artistry capabilities",
        text_3: "â€¢	Consumption of REST API and WS ",
        text_4: "â€¢	Web3 knowledge, including DAPS development experience",
        text_5: "â€¢	Understanding of problems associated with distributed virtual environments (Docker and Cloud Instances)",
        text_6: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, Redis, ...) knowledge",
        text_7: "â€¢	Git version control",
        text_8: "Additional things we will consider are ...",
        text_9: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_10: "â€¢	You have worked with international teams",
        text_11: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_4:{
        title: "PYTHON / DJANGO DEVELOPER",
        type: "IT",
        text_1: "â€¢	Broad background in programing Python 3 and understanding of its module ecosystem",
        text_2: "â€¢	Django framework knowledge",
        text_3: "â€¢	Celery task distribution (using AMPQ backend)",
        text_4: "â€¢	Both creation and consumption of REST API and WS (Django Channels, Django Restframework) and OAUTH2.0",
        text_5: "â€¢	Web3 knowledge",
        text_6: "â€¢	Understanding of problems associated with distributed virtual environments (Docker and Cloud Instances)",
        text_7: "â€¢	Both SQL and NOSQL backends (Firebase, MySQL, Redis, ...) knowledge",
        text_8: "â€¢	Git version control",
        text_9: "Additional things we will consider are ...",
        text_10: "â€¢	You have more than 3 years of experience in devops on consultancy or high-growth startups",
        text_11: "â€¢	You have worked with international teams",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_5:{
        title: "3D GENERALIST",
        type: "MARKETING",
        text_1: "â€¢	Must be a strong and experienced 3d generalist with experience working in a fast-paced environment",
        text_2: "â€¢	Relevant technical training in different fields of the 3d production",
        text_3: "â€¢	Knowledge of 3d modeling software",
        text_4: "â€¢	Knowledge of texturing and shading software",
        text_5: "â€¢	Knowledge of lighting and rendering software",
        text_6: "â€¢	Knowledge of editing and compositing software, in 3d and 2d",
        text_7: "â€¢	Strong understanding of 3d production workflows, storage, asset management and archive",
        text_8: "â€¢	Excellent written and verbal communication skills",
        text_9: "â€¢	Previous experience in an agency or video/animation production company",
        text_10: "Additional things we will consider are ...",
        text_11: "â€¢	You have worked with international teams.",
        text_12: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_6:{
        title: "3D VIDEO EDITOR",
        type: "MARKETING",
        text_1: "â€¢	Must be a strong and experienced video editor and motion designer with experience working in a fast-paced environment",
        text_2: "â€¢	Relevant technical training in video and digital design/production.",
        text_3: "â€¢	Knowledge of Adobe Creative Cloud, specifically Premiere, After Effects, Photoshop, and Illustrator",
        text_4: "â€¢	Color correction and grading skills",
        text_5: "â€¢	Strong understanding of post-production workflows, storage, asset management and archive",
        text_6: "â€¢	Excellent written and verbal communication skills",
        text_7: "â€¢	Previous experience in an agency or video/animation production company",
        text_8: "Additional things we will consider are ...",
        text_9: "â€¢	You have worked with international teams.",
        text_10: "â€¢	You are fluent both in English and Spanish and/or other languages",
      },
      job_7:{
        title: "AGILE COACH / SCRUM MASTER",
        type: "IT",
        text_1: "â€¢	Manage all aspects of project development for multiple digital initiatives for a variety of internal clients.",
        text_2: "â€¢	Develop and demonstrate an understanding of the customer business, needs, expectations, and success factors.",
        text_3: "â€¢	Schedule and manage all resources required to develop the project and ensure timely integration, productivity, and efficient use of resources",
        text_4: "â€¢	Deliver projects on time, on budget, and within scope, while adhering to the standard development and design process of the company",
        text_5: "â€¢	Main contact for client and internal communications regarding project deliverables, status, financial status",
        text_6: "â€¢	Completes agreed work within established estimates and communicates status and issues promptly",
        text_7: "Requirements:",
        text_8: "â€¢	Leadership experience as Scrum Master or in a similar function",
        text_9: "â€¢	Project management certification (PMP or equivalent) is a plus",
        text_10: "â€¢	Solid understanding of the design processes for digital solutions as well as creative production and deliverables. Including UX Resarch, UX and UI Design",
        text_11: "â€¢	Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies",
        text_12: "â€¢	Solid understanding of the full web design and mobile development life cycle",
        text_13: "â€¢	Ability to facilitate a solution-oriented approach to managing projects",
        text_14: "â€¢	Excellent communication skills with the ability to effectively convey complex information at all levels",
        text_15: "â€¢	Strong experience with MS Tools: MS Project, Visio, Powerpoint, Word, Excel",
        text_16: "â€¢	Agile Development Methodologies and tools (Confluence, Planner)",
        text_17: "We will additionally consider:",
        text_18: "â€¢	Onsite/offshore and outsourcing experience.",
        text_19: "â€¢	Passion and knowledge to motivate your team with a servant-leadership style",
        text_20: "â€¢	Enjoy working with interdisciplinary teams in a dynamic environment and appreciate the ex-change with specialists in blockchain, programming and 3D development",
        text_21: "â€¢	Several years of experience in agile software development, ideally in an international scaled environment, and you would like to make a big difference by taking responsibility for coordination and organization",
      },
      job_8:{
        title: "CFO",
        type: "MANAGEMENT",
        text_1: "â€¢	Working alongside the CEO and Board of Directors",
        text_2: "â€¢	Create and present financial and tax strategy recommendations to CEO",
        text_3: "â€¢	Play an integral role in leading all internal and external financial decisions as the company continues to expand",
        text_4: "â€¢	Leading all outward-facing financing activities and communications of the company with current and prospective investors, investment bankers, and capital markets",
        text_5: "â€¢	Assess and evaluate financial performance with regards to both short-term and long-term growth targets and operational KPI's, budgets and forecasts",
        text_6: "â€¢	Ensure compliance with the law and company's policies",
        text_7: "â€¢	Cooperates with Legal and Tax Advisors",
        text_8: "â€¢	Prepare financial statements and reports",
        text_9: "â€¢	Ensure legal compliance on all financial functions",
        text_10: "â€¢	Manage relationships with banks",
        text_11: "â€¢	Building a risk management",
        text_12: "Requirements:",
        text_13: "â€¢	3+ years' experience in Executive Finance Management",
        text_14: "â€¢	Previous experience as CFO or similar; preferably within a growth-stage start-up",
        text_15: "â€¢	Really high interest in the crypto market and derivatives (DeFi, smartcontracts, NTFs, ...) ",
        text_16: "â€¢	Previous experience of building and managing small teams",
        text_17: "â€¢	Some understanding of various business functions: sales, marketing, law and operations",
        text_18: "â€¢	Experience working in a multicultural environment",
        text_19: "â€¢	Outstanding organisational and leadership skills",
        text_20: "â€¢	Excellent interpersonal and communication skills",
        text_21: "â€¢	You are fluent both in English and Spanish and/or other languages.",
      },
      job_9:{
        title: "PR & COMMUNICATION MANAGER (FREELANCE)",
        type: "MARKETING",
        text_1: "â€¢	Relevant technological articles in Tier 1 news media",
        text_2: "â€¢	Knowledge of web3, blockchain and metaverse",
        text_3: "â€¢	Very well connected in the media and press industry",
        text_4: "Additional things we will consider are ...",
        text_5: "â€¢	You have worked with international teams.",
        text_6: "â€¢	You are fluent both in English and Spanish and/or other languages.",
        text_7: "â€¢	Leadership capacity",
        text_8: "â€¢	Experience in team management",
      },
      // The rest of jobs
      popup:{
        title: "Â¿TÃš QUÃ‰ SACAS DE ESTO?",
        title_text_1: "Alto nivel de exigencia: ",
        text_1: "aceptamos el reto de aprender dÃ­a a dÃ­a, de mejorar en nuestras funciones y de aportar valor al futuro. Nos gusta trabajar impulsados por la motivaciÃ³n del proyecto, el trabajo en equipo y el desarrollo constante.",
        title_text_2: "CompaÃ±eros/Equipo:",
        text_2: "somos una comunidad joven y dinÃ¡mica que disfruta creando y desarrollando en equipo la tecnologÃ­a del futuro, apoyada por los mejores y mÃ¡s talentosos profesionales, entusiasmados y con gran visiÃ³n ante los nuevos retos. Dentro de Gamium, la diversiÃ³n, la colaboraciÃ³n, el buen ambiente y la profesionalidad van de la mano.",
        title_text_3: "Crecimiento y Desarrollo:",
        text_3: "queremos que la persona que se incorpore a nuestro equipo conozca los procesos internos y el negocio, y sea capaz de crecer y desarrollarse con nosotros, trabajando en un entorno en el que el talento se respira en cada rincÃ³n. La motivaciÃ³n, energÃ­a y las ganas de aprender son claves para formar parte del equipo de Gamium.",
        title_text_4: "MÃ¡xima autonomÃ­a:",
        text_4: "creemos en la independencia para llevar a cabo nuestras tareas. Perseguimos nuestros objetivos e insistimos en dar la mejor versiÃ³n de nosotros mismos mientras construimos el futuro dentro de Gamium.",
        title_text_5: "Flexibilidad: ",
        text_5: "en Gamium nos preocupamos por el bienestar de nuestros colaboradores y por ello sabemos compaginar nuestro trabajo con la vida personal para ser mÃ¡s efectivos, somos flexibles porque todos tenemos un objetivo comÃºn y estamos comprometidos.",
        title_text_6: "Totalmente remoto:",
        text_6: "creemos en el trabajo remoto ya que parte de nuestro equipo lo harÃ¡ desde Barcelona y desde Bali, por lo que podrÃ¡s trabajar desde donde prefieras y sentirte mÃ¡s productivo y comprometido con las funciones a desempeÃ±ar.",
        title_text_7: "Salario competitivo:",
        text_7: "te ofrecemos un salario fijo y variable en Tokens (valorable segÃºn perfil y experiencia).",
        button: "Cerrar",
      },
    },
    faqs:{
      nav_bar:{
        nav_bar_title: "About",
        nav_bar_element_1: "Gamium",
        nav_bar_element_2: "El Avatar",
        nav_bar_element_3: "El Metaverso",
        nav_bar_element_4: "Tokens",
        nav_bar_element_5: "LAND's",
      },
      faqs_body:{
        element_1:{
          title: "ACERCA DE GAMIUM",
          faq_0:{
            title: "Â¿QuÃ© es Gamium?",
            text_1: "Gamium es una empresa de tecnologÃ­a Web3 y Metaverso cuya misiÃ³n es crear el primer Metaverso que los interconecte a todos, haciendo que los Avatares y los activos sean compatibles entre Metaversos.",
          },
          faq_1:{
            title: "Â¿De dÃ³nde viene el nombre de Gamium?",
            text_1: "Estamos construyendo la base social de la Web3 y el Metaverso. A diferencia de las plataformas sociales actuales, queremos crear una tecnologÃ­a 'sana' que aporte valor a la sociedad, pero al mismo tiempo sabemos que las tecnologÃ­as deben tener algÃºn tipo de entretenimiento. Â¿La soluciÃ³n? La mezcla perfecta de 'Premium' y 'GamificaciÃ³n'.  Â¡Gamium!",
          },
          faq_2:{
            title: "Â¿QuÃ© tecnologÃ­a estÃ¡ desarrollando Gamium?",
            text_1: "- El Avatar: Una identidad digital que puede ser utilizada en todas las aplicaciones Web3 y Metaversos, permitiendo una interoperabilidad y usabilidad Ãºnicas.",
            text_2: "- El Metaverso Social Descentralizado: Un mundo virtual que permite a todo el mundo construir lo que quiera a travÃ©s del SDK de Gamium.",
          },
          faq_3:{
            title: "Â¿CuÃ¡ntos tokens fungibles tiene Gamium?",
            text_1: "Gamium tiene 2 tokens:",
            text_2: "- GMM: El token de gobernanza y medio de intercambio de todo el ecosistema de Gamium.",
            text_3: "- MST: El token de utilidad del Metaverso de Gamium.",
          },
          faq_4:{
            title: "Â¿CuÃ¡ntos tokens no fungibles (NFT) tiene Gamium?",
            text_1: "- Avatares: La identidad digital de los humanos. NFTs de alma gemela (intransferibles).",
            text_2: "- LANDs: Trozos de terreno del Metaverso de Gamium.",
            text_3: "- Edificios: Edificios 3D para utilizar en cualquier Metaverso.",
            text_4: "- ASSETs: Objetos 3D para utilizar en cualquier Metaverso.",
          },
          faq_5:{
            title: "Â¿Es Gamium gratuito?",
            text_1: "El Ãºnico requisito para utilizar Gamium es tener un Avatar - identidad digital. AsÃ­ que los usuarios tendrÃ¡n que mintear su Avatar para utilizar la gran mayorÃ­a de sus funciones. El Avatar no es gratuito para evitar que los bots ataquen nuestro ecosistema (si lo atacan, al menos tienen que pagar por ello). El precio del Avatar minting serÃ¡ muy bajo.",
          },
          faq_6:{
            title: "Â¿Se necesita un Avatar para acceder al Metaverso de Gamium?",
            text_1: "SÃ­. La tecnologÃ­a de los Avatares permite una funcionalidad increÃ­ble para los Metaversos, por eso es un requisito tener un Avatar para acceder al Metaverso de Gamium.",
          },
          faq_7:{
            title: "Â¿QuÃ© incluye el ecosistema Gamium?",
            text_1: "El ecosistema de Gamium incluye el Metaverso Gamium y todas las aplicaciones que integran nuestro Avatar SDK.",
          },
          faq_8:{
            title: "Â¿QuÃ© es el Socialize-to-Earn?",
            text_1: "Al igual que el modelo Play-to-Earn, nuestra economÃ­a potencia lo que llamamos Socialize-to-Earn, un sistema de socializaciÃ³n innovador que permite a los Avatares monetizar el valor creado por sus interacciones sociales.",
          },
          faq_9:{
            title: "Â¿QuiÃ©n es el equipo que estÃ¡ detrÃ¡s de Gamium?",
            text_1: "Nuestro equipo estÃ¡ formado por gente joven y visionaria con una gran capacidad tÃ©cnica necesaria para desarrollar nuevas tecnologÃ­as innovadoras. Somos un equipo de soÃ±adores con un objetivo en mente: construir la tecnologÃ­a del maÃ±ana.",
            text_2: "https://whitepaper.gamium.world/details/team",
          },
          faq_10:{
            title: "Â¿QuiÃ©nes son los principales partners e inversores de Gamium?",
            text_1: "DAO Maker, Metrix Capital, Magnus Capital, Vent Finance, Master Ventures, Venly , Unanimous VC, Peech Capital, ZBS Capital, RR2, Atesis Capital, Parachain Ventures, Mr Beast , Willyrex, Anthony Pompliano, Healthy Pockets, Kmanu, Reven, The Moon Carl, Dustin Plantholt, Diario Cripto, Supra Oracles, GameRich, Zoopa, y muchos mÃ¡s.",
          },
          faq_11:{
            title: "Â¿CuÃ¡ntos tokens no fungibles (NFTs) tiene Gamium?",
            text_1: "-Avatares: La identidad digital de los humanos. Soulmate NFT (no transferible)",
            text_2: "-LANDs: Porciones de LAND del Metaverso Gamium.",
            text_3: "-Edificios: Edificios 3D para usar en cualquier metaverso.",
            text_4: "-ASSETs: objetos 3D para usar en cualquier metaverso.",
          }
        },
        element_2:{
          title: "ACERCA DEL AVATAR",
          faq_1:{
            title: "Â¿QuÃ© es el Avatar?",
            text_1: "El Avatar es una identidad digital representada por un alma gemela NFT que reÃºne todas las huellas digitales de un usuario en una entidad unificada. Estas huellas digitales incluyen anatomÃ­as en 3D y datos on-chain y off-chain.",
          },
          faq_2:{
            title: "Â¿QuÃ© tecnologÃ­as utiliza el Avatar?",
            text_1: "NFT, tecnologÃ­a blockchain, firmas digitales, IA, modelado de datos, anÃ¡lisis forense.",
          },
          faq_3:{
            title: "Â¿QuÃ© tipo de datos se almacenan en el Avatar?",
            text_1: "Datos on-chain y off-chain.",
          },
          faq_4:{
            title: "Â¿QuÃ© tipo de datos pueden almacenar los Avatares?",
            text_1: "Todo tipo de datos relacionados con datos on-chain. Con nuestro modelado de datos, podemos extraer transacciones, holdings, protocolos utilizados, evaluaciones de holder, evaluaciones DeFi, holding de NFTs, perfiles de usuario, representaciones latentes, grÃ¡ficos de transacciones, y muchos mÃ¡s.",
            text_2: "Todo tipo de datos off-chain, como informaciÃ³n de redes sociales (seguidores, amigos...), informaciÃ³n de juegos, tÃ­tulos de educaciÃ³n, registros mÃ©dicos... Infinitas posibilidades.",
          },
          faq_5:{
            title: "Â¿CÃ³mo se estructuran los datos?",
            text_1: "Todos los datos de Avatar estÃ¡n estructurados en KPIs Ãºtiles - logros. Se puede acceder a estos KPIs a travÃ©s de una llamada de API utilizando el Avatar SDK.",
          },
          faq_6:{
            title: "Â¿CÃ³mo se configura la privacidad de los Avatares?",
            text_1: "Cada usuario puede asignar la privacidad de cada KPI. Creemos firmemente en la privacidad.",
          },
          faq_7:{
            title: "Â¿Tiene el Avatar una representaciÃ³n en 3D?",
            text_1: "SÃ­. Aparte de datos, un Avatar tiene tambiÃ©n anatomÃ­as, que son representaciones 3D del Avatar en un entorno 3D.",
          },
          faq_8:{
            title: "Â¿Puedo personalizar mi Avatar?",
            text_1: "Cada Avatar puede tener mÃºltiples anatomÃ­as de diferentes proveedores. Algunas son mÃ¡s realistas, otras mÃ¡s low poly. Los usuarios pueden personalizar estas anatomÃ­as cuando lo deseen.",
          },
          faq_9:{
            title: "Â¿QuÃ© es el Avatar SDK?",
            text_1: "El Avatar SDK es la herramienta que utilizan las aplicaciones para integrar las identidades digitales del Avatar. Esta herramienta incluye un social login (como el inicio de sesiÃ³n con Facebook) en el que, al iniciar sesiÃ³n en cualquier aplicaciÃ³n, el usuario puede dar permiso a la aplicaciÃ³n para acceder a informaciÃ³n especÃ­fica de sus datos de Avatar. Esta informaciÃ³n puede ser utilizada por la aplicaciÃ³n para aumentar el valor de sus productos o servicios.",
          },
          faq_10:{
            title: "Â¿QuÃ© aplicaciones pueden utilizar el Avatar SDK?",
            text_1: "Literalmente, cualquier aplicaciÃ³n Web3 o Metaverso puede integrar nuestro Avatar SDK. ",
            text_2: "Ejemplos de aplicaciones que pueden empezar a utilizar nuestro SDK son Launchpads, aplicaciones DeFi, portales de empleo, DAOs...",
          },
        },
        element_3:{
          title: "ACERCA DEL METAVERSO SOCIAL DESCENTRALIZADO",
          faq_1:{
            title: "Â¿QuÃ© es un Metaverso Social?",
            text_1: "Un Metaverso Social es un Metaverso centrado en las interacciones y las caracterÃ­sticas sociales.",
          },
          faq_2:{
            title: "Â¿CÃ³mo es el Metaverso de Gamium?",
            text_1: "El Metaverso de Gamium estÃ¡ compuesto por la ciudad de Genesis, Islas y servidores de Comunidad. Genesis estÃ¡ en el centro rodeada de Islas.",
          },
          faq_3:{
            title: "Â¿QuÃ© podemos encontrar en Genesis?",
            text_1: "Genesis es el lugar en el centro Gamium donde se encuentran los edificios de Gamium. En Genesis tambiÃ©n encontrarÃ¡s experiencias inmersivas y eventos diarios exclusivos.",
          },
          faq_4:{
            title: "Â¿QuÃ© son los edificios de Gamium?",
            text_1: "Estos edificios contienen aplicaciones Ãºnicas como chats descentralizados, aplicaciones de llamadas en 3D, aplicaciones DeFi y portales de empleo.",
          },
          faq_5:{
            title: "Â¿QuÃ© podemos encontrar en las Islas?",
            text_1: "Fuera de Genesis hay Islas, que son lugares exclusivos para que los Avatares vivan y construyan lo que quieran. Utilizando el Gamium SDK en su LAND, los Avatares pueden construir su casa, crear objetos 3D, crear eventos exclusivos, integrar su tienda de comercio electrÃ³nico, anunciar o alquilar su espacio y mucho mÃ¡s.",
          },
          faq_6:{
            title: "Â¿QuÃ© son los servidores de Comunidad?",
            text_1: "Los servidores de Comunidad son ciudades exclusivas para comunidades. Tienes que ser miembro de esa comunidad para acceder al servidor comunitario. Los miembros de la comunidad tambiÃ©n pueden interactuar y construir con el Gamium SDK. Pronto se revelarÃ¡ mÃ¡s informaciÃ³n interesante.",
          },
          faq_7:{
            title: "Â¿SerÃ¡ fÃ¡cil construir algo en el metaverso de Gamium?",
            text_1: "SÃ­, estamos desarrollando un Gamium SDK fÃ¡cil de usar para nuestros Avatares.",
          },
          faq_8:{
            title: "Â¿QuÃ© es el Gamium SDK?",
            text_1: "El Gamium SDK es una herramienta de construcciÃ³n sin cÃ³digo. Los Avatares podrÃ¡n construir ASSETs 3D (objetos 3D), experiencias y conectar aplicaciones con el Gamium SDK.",
          },
          faq_9:{
            title: "Â¿A quiÃ©n pertenece el Metaverso de Gamium?",
            text_1: "El Metaverso de Gamium es propiedad de sus Avatares. La mayorÃ­a de las experiencias, aplicaciones y ASSETs del Metaverso son de Avatares para Avatares.",
          },
          faq_10:{
            title: "Â¿DÃ³nde puedo encontrar las LANDs y edificios?",
            text_1: "La mayorÃ­a de las LANDs se encuentran en las Islas. Los edificios pueden estar ubicados en cualquier lugar del Metaverso. Puedes trasladar los edificios que poseas a tu LAND.",
          },
          faq_11:{
            title: "Â¿Existe un mercado de NFTs?",
            text_1: "SÃ­, el Metaverso de Gamium tiene un mercado nativo de NFTs para LANDs, edificios y ASSETs.",
          },
          faq_12:{
            title: "Â¿Cualquiera puede crear sus propios ASSETs y comerciar con ellos en el mercado?",
            text_1: "SÃ­, todos los Avatares pueden crear ASSETs en 3D y subirlos a nuestro mercado de NFTs (nosotros nos encargamos del minting). Los Avatares tambiÃ©n pueden crear colecciones y aÃ±adir royalties por las ventas secundarias.",
          },
        },
        element_4:{
          title: "ACERCA DE LOS TOKENS",
          faq_1:{
            title: "Â¿CuÃ¡ntos tokens fungibles tiene Gamium?",
            text_1: "Gamium tiene 2 tokens fungibles:",
            text_2: "- GMM: El token de gobernanza e intercambio de todo el ecosistema de Gamium.",
            text_3: "- MST: El token de utilidad del Metaverso de Gamium.",
          },
          faq_2:{
            title: "Â¿CuÃ¡ntos tokens no fungibles (NFT) tiene Gamium?",
            text_1: "- Avatares: La identidad digital de los humanos. NFTs de alma gemela (intransferible).",
            text_2: "- LANDs: Trozos de terreno del Metaverso de Gamium.",
            text_3: "- Edificios: Edificios 3D para utilizar en cualquier Metaverso.",
            text_4: "- ASSETs: Objetos 3D para utilizar en cualquier Metaverso.",
          },
          faq_3:{
            title: "Â¿En quÃ© blockchains se despliegan los tokens de Gamium?",
            text_1: "- GMM: Binance Smart Chain (BSC)",
            text_2: "- MST: Por anunciar",
            text_3: "- Avatares: Binance Smart Chain (BSC)",
            text_4: "- LANDs: Ethereum",
            text_5: "- Edificios: Ethereum",
            text_6: "- ASSETs: Por anunciar",
          },
          faq_4:{
            title: "Â¿QuiÃ©n ha auditado los tokens?",
            text_1: "Certik, la empresa lÃ­der en seguridad de blockchain a nivel mundial.",
          },
          faq_5:{
            title: "Â¿Para quÃ© se utiliza $GMM?",
            text_1: "- Gobernanza de Avatar",
            text_2: "- Gobernanza del Metaverso",
            text_3: "- Servidores comunitarios abiertos",
            text_4: "- Acceder a drops exclusivos",
            text_5: "- Recibir airdrops",
            text_6: "- ModeraciÃ³n descentralizada del Metaverso",
            text_7: "- Acceder a eventos exclusivos",
          },
          faq_6:{
            title: "Â¿CuÃ¡l es la oferta mÃ¡xima de tokens GMM y el precio inicial?",
            text_1: "La oferta mÃ¡xima es de 50.000.000.000 tokens y el precio inicial es de 0,0003$.",
          },
          faq_7:{
            title: "Â¿CuÃ¡ndo saldrÃ¡ a la venta GMM?",
            text_1: "En marzo de 2022, Â¡estate atento!",
          },
          faq_8:{
            title: "Â¿CuÃ¡l es la direcciÃ³n del contrato del token GMM?",
            text_1: "EstÃ¡ por anunciar.",
          },
          faq_9:{
            title: "Â¿QuÃ© es el staking de GMM?",
            text_1: "Es una funcionalidad Ãºtil que revelaremos muy pronto. Â¡SerÃ¡ una gran sorpresa!",
          },
          faq_10:{
            title: "Â¿Para quÃ© se utiliza el MST?",
            text_1: "Es la moneda del Metaverso de Gamium. Cualquier tipo de transacciÃ³n dentro del Metaverso de Gamium se harÃ¡ con MST.",
          },
          faq_11:{
            title: "Â¿CuÃ¡ndo saldrÃ¡ a la venta el MST?",
            text_1: "En el segundo trimestre de 2022, Â¡estate atentos!",
          },
          faq_12:{
            title: "Â¿CuÃ¡ndo estarÃ¡n disponibles las LANDs, edificios y ASSETs?",
            text_1: "Lo anunciaremos muy pronto. Â¡SerÃ¡ una gran sorpresa!",
          },
          faq_13:{
            title: "Â¿PodrÃ© comerciar con LANDs, Buildings, ASSETs NFTs en OpenSea?",
            text_1: "Â¡SÃ­!",
          },
        },
        element_5:{
          title: "SOBRE LAS LANDS",
          faq_1:{
            title: "Â¿CÃ³mo es el metaverso de Gamium?",
            text_1: "El metaverso de Gamium estÃ¡ compuesto por GÃ©nesis, 10 Islas y Servidores de Comunidad. GÃ©nesis estÃ¡ en el centro, rodeado de las mÃºltiples Islas.",
          },
          faq_2:{
            title: "Â¿DÃ³nde puedo encontrar las LANDs y los edificios?",
            text_1: "La mayorÃ­a de los terrenos se encuentran en las islas. Los edificios pueden estar ubicados en cualquier lugar del Metaverso. Puedes trasladar los edificios que poseas a tu LAND.",
          },
          faq_3:{
            title: "Â¿QuÃ© tamaÃ±o tienen los TERRENOS?",
            text_1: "Las LANDs se describen en unidades, siendo 16 metros equivalentes a una unidad. Las LANDs de Gamium son rectangulares y tienen 7 tamaÃ±os diferentes: 1x1, 1x2, 2x2, 2x3, 3x3, 3x5 o 5x5.",
            text_2: "Una LAND 1x1 tiene 16m x 16m, es decir, 256 m2, con un total de 100.000 unidades cuadradas a la venta.",
          },
          faq_4:{
            title: "Â¿CuÃ¡ndo serÃ¡ la primera fecha de venta de las LAND?",
            text_1: "El primer drop se producirÃ¡ muy pronto. Cada 3 semanas habrÃ¡ un drop de islas hasta que se hayan poblado todas.",
          },
          faq_5:{
            title: "Â¿CÃ³mo funciona la venta de LANDs?",
            text_1: "Las LANDs se venderÃ¡n en drops. MÃ¡s concretamente, habrÃ¡ 1 drop cada 3 semanas para cada una de las islas del metaverso de Gamium. Cada drop tiene su propia temÃ¡tica, estilo e influencers. QuizÃ¡s puedas tener vecinos famosos. HabrÃ¡ preventa, venta primaria y venta secundaria. Lo anunciaremos muy pronto.",
          },
          faq_6:{
            title: "Â¿QuÃ© puedes hacer con una LAND?",
            text_1: "â—	Construir experiencias sociales",
            text_2: "â—	Conectar con internet y blockchains con un solo clic",
            text_3: "â—	Compras en lÃ­nea",
            text_4: "â—	Hacer publicidad",
            text_5: "â—	Alquilar",
            text_6: "â—	Gobernanza de los barrios",
          },
          faq_7:{
            title: "Â¿QuÃ© precios tendrÃ¡n las LAND?",
            text_1: "HabrÃ¡ diferentes precios dependiendo de la zona del LAND.",
            text_2: "Lo anunciaremos pronto.",
          },
        },
      },
    },
  },
};